config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  resources :plants
  resources :groups do 
    resources :plants
  end
  resources :plants do 
    resources :sensor
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/datapoint.rb
# frozen_string_literal: true

class Datapoint < ApplicationRecord
  validates_presence_of :sensor_id
  validates_presence_of :value
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  has_many :plants
  has_many :sensors, through: :plants
end

app/models/plant.rb
# frozen_string_literal: true

class Plant < ApplicationRecord
  belongs_to :group
  has_many :sensors, class_name: "sensors", foreign_key: "sensor_id"
end

app/models/sensor.rb
# frozen_string_literal: true

class Sensor < ApplicationRecord
  validates_presence_of :hardware_id
  belongs_to :plant, optional: true
  belongs_to :plant, optional: true
  has_many :datapoints, class_name: "datapoint", foreign_key: "reference_id"
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/datapoint_controller.rb
# frozen_string_literal: true

class DatapointController < ApplicationController
  def normalize(data, high, low)
    (1 - ((data - high) / (low - high)))
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group = Group.new
  end

  def create
    @group = Group.create(params[:name])
    redirect_to group_path(@group)
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(params)
      redirect_to @group, notice: "Shelf was successfully updated."
    else
      render :edit
    end
  end

  def show
    @group = Group.find(params[:id])
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

# This is the pages controller
class PagesController < ApplicationController
  def index
    @group = Group.all
    @plant = Plant.all
  end
end

app/controllers/plants_controller.rb
# frozen_string_literal: true

class PlantsController < ApplicationController
  def new
    @group = Group.find(params[:id])
    @plant = Plant.new
  end

  def show
    @plant = Plant.find(params[:id])
  end

  def edit
    @plant = Plant.find(params[:id])
  end

  def update
    @plant = Plant.find(params[:id])
    if @plant.update(params)
      redirect_to @plant, notice: "Plant was successfully updated."
    else
      render :edit
    end
  end
end

app/controllers/sensor_controller.rb
# frozen_string_literal: true

class SensorController < ApplicationController
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/datapoint_helper.rb
# frozen_string_literal: true

module DatapointHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/plants_helper.rb
# frozen_string_literal: true

module PlantsHelper
end

app/helpers/sensor_helper.rb
# frozen_string_literal: true

module SensorHelper
end

app/views/groups/new.html.erb
<%= simple_form_for @group do |f| %>
  <%= f.input :name %>
    <%= f.button :submit %>

<% end %>

app/views/groups/show.html.erb
<%= @group.name%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SturdyPancakeServer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
    <div class="home-banner text-center p-5">
        <h1>Plants</h1>
    </div>
    <div class="row justify-content-center">
        <% Plant.all.each do |plant| %>
        <div class="col-lg-4 col-12  p-2">

            <div class="card" style="height: 100%;">
                <div class="card-body">
                <div class="card-title text-center">
                    <p><strong><%= link_to plant.name , plant_path(plant)%> </strong></p>
                </div>
                <div class="card-text">
                <% sensor = Sensor.where(plant_id: plant.id).first%>
                <%= sensor.Sensor_Type %>
                <% dp = Datapoint.where(sensor_id: sensor.id) %>
                <% unless dp.empty?%>
                <%= Datapoint.where(sensor_id: sensor.id).last.value%>   
                <% end %>             
                </div>
            </div>
            </div>
        </div>


        <% end %>
    </div>
    

app/views/plants/show.html.erb
<%= @plant.name %>
                <%= Sensor.where(plant_id: @plant.id).first%>